//@ {
//@	 "targets":[{"name":"adda.o","type":"object"}]
//@	}

#include "adda.h"
#include "file_out.h"
#include "grid.h"

using namespace SnowflakeModel;

void SnowflakeModel::addaShapeWrite(const Grid& grid,FileOut&& dest)
	{
	auto min=grid.minGet();
	auto size=grid.sizeGet();
	auto step=grid.stepGet();
	dest.printf("# ADDA geometry file generated by snowflake-toolkit\n")
		.printf("# Bounding box starts at (%.7g,%.7g,%.7g)\n"
			,min.x,min.y,min.z)
		.printf("# Number of divisions are (%d,%d,%d)\n",size.x,size.y,size.z)
		.printf("# Step sizes are (%.7g,%.7g,%.7g)\n",step.x,step.y,step.z);

	grid.pointsVisit([&dest](int x,int y,int z,uint8_t value)
		{
		if(value)
			{dest.printf("%d %d %d\n",x,y,z);}
		});
	}