function [stats]=graupel_generate(paramstruct,exepath)
	seed=ternary(@()isfield(paramstruct,'seed')...
		,@()['--seed=',int2str(paramstruct.seed)]...
		,@()'');

	scale=ternary(@()isfield(paramstruct,'scale')...
		,@()['--scale=[',num2str(paramstruct.scale.mean),',',num2str(paramstruct.scale.std),']']...
		,@()'');

	E_0=ternary(@()isfield(paramstruct,'E_0')...
		,@()['--E_0=',num2str(paramstruct.E_0)]...
		,@()'');

	decay_distance=ternary(@()isfield(paramstruct,'decay_distance')...
		,@()['--decay-distance=',num2str(paramstruct.decay_distance)]...
		,@()'');

	merge_offset=ternary(@()isfield(paramstruct,'merge_offset')...
		,@()['--merge-offset=',num2str(paramstruct.merge_offset)]...
		,@()'');

	overlap_max=ternary(@()isfield(paramstruct,'overlap_max')...
		,@()['--overlap-max=',int2str(paramstruct.overlap_max)]...
		,@()'');

	D_max=ternary(@()isfield(paramstruct,'D_max')...
		,@()['--D_max=',num2str(paramstruct.D_max)]...
		,@()'');

	fill_ratio=ternary(@()isfield(paramstruct,'fill_ratio')...
		,@()['--fill-ratio=',num2str(paramstruct.fill_ratio)]...
		,@()'');

	statefile=ternary(@()isfield(paramstruct,'statefile')...
		,@()['--statefile=',paramstruct.statefile]...
		,@()'');

	dump_geometry=ternary(@()isfield(paramstruct,'dump_geometry')...
		,@()['--dump-geometry=',paramstruct.dump_geometry]...
		,@()'');


	dump_geometry_ice=ternary(@()isfield(paramstruct,'dump_geometry_ice')...
		,@()['--dump-geometry-ice=',paramstruct.dump_geometry_ice]...
		,@()'');

	dump_stats=ternary(@()isfield(paramstruct,'dump_stats')...
		,@()['--dump-stats=',paramstruct.dump_stats]...
		,@()'');

	n=nargin();
	cmd=ternary(@()(n<2),@()'graupel_generate2'...
		,@()[exepath,'/graupel_generate2'])

	system_wrapper({cmd,seed,scale,E_0,decay_distance,merge_offset...
		,overlap_max,D_max,fill_ratio,statefile,dump_geometry,dump_geometry_ice...
		,dump_stats},nargout()>0);
	if ~isempty(dump_stats) 
		stats=csvread2(dump_stats,'\t');
	end
end

