function graupel_generate(paramstruct,exepath)
	seed=ternary(@isfield(paramstruct,'seed')...
		,@()['--seed=',int2str(paramstruct.seed)]...
		,@()'');

	scale=ternary(@isfield(paramstruct,'scale')...
		,@()['--scale=[',num2str(paramstruct.scale.mean),',',num2str(paramstruct.scale.std),']']...
		,@()'');

	E_0=ternary(@isfield(paramstruct,'E_0')...
		,@()['--E_0=',num2str(paramstruct.E_0)]...
		,@()'');

	decay_distance=ternary(@isfield(paramstruct,'decay_distance')...
		,@()['--decay-distance=',num2str(paramstruct.decay_distance)]...
		,@()'');

	merge_offset=ternary(@isfield(paramstruct,'merge_offset')...
		,@()['--merge-offset=',num2str(paramstruct.merge_offset)]...
		,@()'');

	overlap_max=ternary(@isfield(paramstruct,'overlap_max')...
		,@()['--overlap-max=',int2str(paramstruct.overlap_max)]...
		,@()'');

	D_max=ternary(@isfield(paramstruct,'D_max')...
		,@()['--D_max=',num2str(paramstruct.D_max)]...
		,@()'');

	fill_ratio=ternary(@isfield(paramstruct,'fill_ratio')...
		,@()['--fill-ratio=',num2str(paramstruct.fill_ratio)]...
		,@()'');

	if nargin()<2
		system_wrapper({'graupel_generate2',seed,E_0,decay_distance,merge_offset...
			,overlap_max,D_max,fill_ratio});
	else
		system_wrapper({[exepath,'/graupel_generate2'],seed,E_0,decay_distance,merge_offset...
			,overlap_max,D_max,fill_ratio});
	end
end

function result=ternary(cond,if_true,if_false)
	if cond()
		result=if_true();
	else
		result=if_false();
	end
end
