function mod34_lambda_corr_plot(table)
	y_min=min([table(:,4);table(:,6)]);
	y_max=max([table(:,4);table(:,6)]);
	corrplot(table(:,1),table(:,4),'$R_g\times 10^{-7}$','$\gamma_\text{cloud}$','../report'...
		,'output/mod34-rg-lambda-cloud.pdf',1e7,1,[],[y_min y_max]);
	corrplot(table(:,1),table(:,6),'$R_g\times 10^{-7}$','$\gamma_\text{dropped}$','../report'...
		,'output/mod34-rg-lambda-dropped.pdf',1e7,1,[],[y_min y_max]);

	corrplot(table(:,2),table(:,4),'$R_m\times 10^{-3}$','$\gamma_\text{cloud}$','../report'...
		,'output/mod34-rm-lambda-cloud.pdf',1e3,1,[],[y_min y_max]);
	corrplot(table(:,2),table(:,6),'$R_m\times 10^{-3}$','$\gamma_\text{dropped}$','../report'...
		,'output/mod34-rm-lambda-dropped.pdf',1e3,1,[],[y_min y_max]);

	corrplot(table(:,3),table(:,4),'$R_d\times 10^{-4}$','$\gamma_\text{cloud}$','../report'...
		,'output/mod34-rd-lambda-cloud.pdf',1e4,1,[],[y_min y_max]);
	corrplot(table(:,3),table(:,6),'$R_d\times 10^{-4}$','$\gamma_\text{dropped}$','../report'...
		,'output/mod34-rd-lambda-dropped.pdf',1e4,1,[],[y_min y_max]);
end
