//@	{
//@	    "dependencies_extra":[],
//@	    "targets":[
//@	        {
//@	            "dependencies":[],
//@	            "name":"voxelbuilder_adda.o",
//@	            "type":"object"
//@	        }
//@	    ]
//@	}
#include "voxelbuilder_adda.h"
#include "volume_convex.h"
#include "file_out.h"
#include <cstring>

using namespace SnowflakeModel;

VoxelbuilderAdda::VoxelbuilderAdda(FileOut& dest,double dx,double dy,double dz
	,const BoundingBox& bounding_box):r_dest(dest),m_bounding_box(bounding_box)
	{
	auto range=bounding_box.m_max - bounding_box.m_min;
	m_n_x=static_cast<int>( ceil( range.x/dx ) );
	m_n_y=static_cast<int>( ceil( range.y/dy ) );
	m_n_z=static_cast<int>( ceil( range.z/dz ) );
	m_dx=dx;
	m_dy=dy;
	m_dz=dz;

	r_dest.printf("# ADDA geometry file generated by snowflake generator\n");
	r_dest.printf("# Bounding box is from (%.7g,%.7g,%.7g) to (%.7g,%.7g,%.7g)\n"
		,bounding_box.m_min.x,bounding_box.m_min.y,bounding_box.m_min.z
		,bounding_box.m_max.x,bounding_box.m_max.y,bounding_box.m_max.z);
	r_dest.printf("# Number of divisions are (%d,%d,%d)\n",m_n_x,m_n_y,m_n_z);
	r_dest.printf("# Step sizes are (%.7g,%.7g,%.7g)\n",m_dx,m_dy,m_dz);
	}

VoxelbuilderAdda::VoxelbuilderAdda(FileOut& dest
	,unsigned int n_x,unsigned int n_y,unsigned int n_z
	,const BoundingBox& bounding_box):
	r_dest(dest)
	,m_n_x(n_x),m_n_y(n_y),m_n_z(n_z)
	,m_bounding_box(bounding_box)
	{
	if(m_n_x==0)
		{
		if(n_y > 0)
			{
			m_n_x=n_y*(bounding_box.m_max.x -  bounding_box.m_min.x)
				/(bounding_box.m_max.y -  bounding_box.m_min.y)+ 0.5;
			}
		else
		if(n_z > 0)
			{
			m_n_x=n_z*(bounding_box.m_max.x -  bounding_box.m_min.x)
				/(bounding_box.m_max.z -  bounding_box.m_min.z)+ 0.5;
			}
		else
			{throw "At leas one of Ny and Nz must be grater than zero";}
		}
	
	if(m_n_y==0)
		{
		if(n_x > 0)
			{
			m_n_y=n_x*(bounding_box.m_max.y -  bounding_box.m_min.y)
				/(bounding_box.m_max.x -  bounding_box.m_min.x)+ 0.5;
			}
		else
		if(n_z > 0)
			{
			m_n_y=n_z*(bounding_box.m_max.y -  bounding_box.m_min.y)
				/(bounding_box.m_max.z -  bounding_box.m_min.z)+ 0.5;
			}
		else
			{throw "At leas one of Nx and Nz must be grater than zero";}
		}
	
	if(m_n_z==0)
		{
		if(n_x > 0)
			{
			m_n_z=n_x*(bounding_box.m_max.z -  bounding_box.m_min.z)
				/(bounding_box.m_max.x -  bounding_box.m_min.x)+ 0.5;
			}
		else
		if(n_y > 0)
			{
			m_n_z=n_y*(bounding_box.m_max.z -  bounding_box.m_min.z)
				/(bounding_box.m_max.y -  bounding_box.m_min.y)+ 0.5;
			}
		else
			{throw "At leas one of Nx and Ny must be grater than zero";}
		}
	
	if(m_n_x==0 || m_n_y==0 || m_n_z==0)
		{throw "More points are needed to sample the generated geometry";}
	
	m_data_filled=new uint8_t[m_n_x*m_n_y*m_n_z];
	m_data_stop=new uint8_t[m_n_x*m_n_y*m_n_z];
	
	memset(m_data_filled,0,m_n_x*m_n_y*m_n_z);
	r_dest.printf("# ADDA geometry file generated by snowflake generator\n");
	r_dest.printf("# Bounding box is from (%.7g,%.7g,%.7g) to (%.7g,%.7g,%.7g)\n"
		,bounding_box.m_min.x,bounding_box.m_min.y,bounding_box.m_min.z
		,bounding_box.m_max.x,bounding_box.m_max.y,bounding_box.m_max.z);
	r_dest.printf("# Number of divisions are (%d,%d,%d)\n",m_n_x,m_n_y,m_n_z);

	auto range=bounding_box.m_max - bounding_box.m_min;
	m_dx=range.x/m_n_x;
	m_dy=range.y/m_n_y;
	m_dz=range.z/m_n_z;
	r_dest.printf("# Step sizes are (%.7g,%.7g,%.7g)\n",m_dx,m_dy,m_dz);
	}

VoxelbuilderAdda::~VoxelbuilderAdda()
	{
	delete[] m_data_filled;
	delete[] m_data_stop;
	}

PointInt VoxelbuilderAdda::quantize(const Point& p) const
	{
	auto pos=p-m_bounding_box.m_min;
		
	return PointInt
		{
		 pos.x/m_dx
		,pos.y/m_dy
		,pos.z/m_dz
		,1
		};
	}
	
Point VoxelbuilderAdda::dequantize(const PointInt& p) const
	{
	return Point
		{
		 m_bounding_box.m_min.x + (p.x+0.5)*m_dx
		,m_bounding_box.m_min.y + (p.y+0.5)*m_dy
		,m_bounding_box.m_min.z + (p.z+0.5)*m_dz
		,1
		};
	}
	
void VoxelbuilderAdda::fill(const PointInt& pos)
	{
	r_dest.printf("%d %d %d\n",pos.x,pos.y,pos.z);
	}
